version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_MESSAGE_FORMAT_VERSION=2.8
      - CONNECT_PLUGIN_PATH=/usr/share/java
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka
      - CONNECT_REST_ADVERTISED_PORT=8083
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  control-center:
    image: confluentinc/cp-enterprise-control-center
    ports:
      - 9021:9021
    environment:
      - CONTROL_CENTER_KAFKA_BROKER=kafka:9092
      - CONTROL_CENTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - CONTROL_CENTER_CONNECT_CLUSTER=kafka:8083
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
    depends_on:
      - kafka
      - schema-registry
      - connect
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    depends_on:
      - kafka
  connect:
    image: confluentinc/cp-kafka-connect
    ports:
      - 8083:8083
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC=connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=connect-status
      - CONNECT_PLUGIN_PATH=/usr/share/java
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect
    volumes:
      - ./plugins:/usr/share/java
    depends_on:
      - kafka
